### ISSUE TITLE
artifacts boundary

### ISSUE THREAD

**Issue by fzhang612** [ShenYujun/InterFaceGAN#11]
Hi there,

In the paper the last paragraph of section 3.3 mentions how to fix artifacts using certain hyperplane. However this hyperplane is missing in the boundaries folder of this repo. Are you going to release it soon?

Thanks!

**Comment by ShenYujun** [comment]
Please use `boundary/pggan_celebahq_quality_boundary.npy` for artifacts correction w.r.t. PGGAN model. Since almost all images generated by StyleGAN are with high quality. So we don't provide artifacts boundary for StyleGAN model.
