### ISSUE TITLE
similar to this project?

### ISSUE THREAD

**Issue by ilovecv** [ShenYujun/InterFaceGAN#12]
Hi,

Thank you very much for your great work! But I find it is very similar with this project:
https://github.com/Puzer/stylegan-encoder

What do you think?

Thanks!

**Comment by ShenYujun** [comment]
Thanks for pointing out. "stylegan-encoder" is indeed a great work on inverting the StyleGAN model. But our paper "Interpreting the Latent Space of GANs for Semantic Face Editing" analyzes the latent space of GANs in a general way. We provide theoretical analysis as well as conditional manipulation approach, which is beyond "stylegan-encoder". This repo also supports analyzing other GAN models besides StyleGAN, e.g., ProgressiveGAN or any other cutomized models. Hope this can address your concern.

**Comment by ilovecv** [comment]
thanks!

**Comment by mehameha998** [comment]
I think this paper share a high similarity with TLGAN. What's the difference is this paper provide mathematical proof. Am I right?

**Comment by ShenYujun** [comment]
@mehameha998 You are right that this project does share similar method with TLGAN. However, besides the theoretical proof (which is an important contribution on why this method works and on why we can perform conditional manipulation), we also quantitively analyze the correlations between different semantics, which is barely mentioned in TLGAN. Such analysis sheds light on why GAN learns to encode the correlations in the latent space. Furthermore, we make detailed comparisons between PGGAN and StyleGAN, as well as between Z space and W space of StyleGAN, which are also missing in TLGAN. BTW, TLGAN actually does not result in a paper, and we didn't spot that work before. So, thank you for pointing it out for us :)
