### ISSUE TITLE
no obvious age difference between orignial stylegan and this

### ISSUE THREAD

**Issue by ZhouDongliang** [ShenYujun/InterFaceGAN#13]
I used previous stylegan and stylegan in interfacegan to change age. But I cannot tell obvious difference between these two.
the boundary used is "stylegan_f    fhq_age_w_boundary.npy". Could you provide any help?
![0002](https://user-images.githubusercontent.com/16381762/63921697-de3c7800-ca75-11e9-888f-8f47ea755f7b.jpg)
![0002](https://user-images.githubusercontent.com/16381762/63921699-ded50e80-ca75-11e9-9035-32e03eda9c12.png)

![0007](https://user-images.githubusercontent.com/16381762/63921716-e7c5e000-ca75-11e9-9f2f-812c121a8f99.jpg)
![0007](https://user-images.githubusercontent.com/16381762/63921718-e85e7680-ca75-11e9-8f1c-5e055e7fbb11.png)
![0010](https://user-images.githubusercontent.com/16381762/63921736-f3b1a200-ca75-11e9-8a7a-bca4c5a27486.jpg)
![0010](https://user-images.githubusercontent.com/16381762/63921737-f3b1a200-ca75-11e9-984b-be4af8c30282.png)

**Comment by ShenYujun** [comment]
Do you use the tool `edit.py`? And have you tried adjusting `start_distance` and `end_distance` in file `edit.py`?

**Comment by mehameha998** [comment]
Yeah... I met the same phenomenon use the pretrained ffhq-stylegan model.  I follow the default setting in edit.py. Should I modify some parameters when I use stylegan?

**Comment by mehameha998** [comment]
You should use boundary in Z space.

**Comment by ShenYujun** [comment]
@ZhouDongliang @mehameha998 If you want to use W/W+ space, you should first generate images from Z space, and then use the intermediate latent codes from W/W+ space (which will be automatically saved by `generate_data.py`). Please do not generate W/W+ vectors randomly, since W/W+ space is not subject to standard normal distribution. See NOTE in `edit.py` for more details.

**Comment by ZhouDongliang** [comment]
> @ZhouDongliang @mehameha998 If you want to use W/W+ space, you should first generate images from Z space, and then use the intermediate latent codes from W/W+ space (which will be automatically saved by `generate_data.py`). Please do not generate W/W+ vectors randomly, since W/W+ space is not subject to standard normal distribution. See NOTE in `edit.py` for more details.

OK, thank you for your reply.
