### ISSUE TITLE
How to find more boundaries?

### ISSUE THREAD

**Issue by doantientai** [ShenYujun/InterFaceGAN#19]
Congratulations for the great work!

Please correct me if I'm wrong. From what I understand, providing a pretrained model and a boundary (in boundaries/) we can tuning features of generated images. This is amazing.

I wonder if I can explore other boundaries as well? Let's say, hair color or skin colors? If it is possible, how could I do that?

Thank you very much!

**Comment by ShenYujun** [comment]
Yes, you can do that as long as you have a corresponding model for hair color (or skin color) classification. Then you can treat the boundary search process as a bi-classification problem (e.g. black hair v.s. blond hair).

Please see tool `train_boundary.py` as well as the function `train_boundary()` in file `utils/manipulator.py` for more details.

**Comment by doantientai** [comment]
Thank you @ShenYujun , I will try that

**Comment by krishnamecho** [comment]
@doantientai Were you able to generate new boundaries?

**Comment by pfeducode** [comment]
> @doantientai你能创造新的界限吗？

Can you communicate with me
