### ISSUE TITLE
Issue when using pretrained model with input size 512x512

### ISSUE THREAD

**Issue by doantientai** [ShenYujun/InterFaceGAN#22]
Hi,

I am trying to run generate_data.py using my pretrained model which was trained on 512x512 images. It successfully converted the pkl model to pth, but then showed the error below.

`Traceback (most recent call last):
  File "/media/tai/6TB/Projects/InterFaceGAN/InterFaceGAN/generate_data.py", line 114, in <module>
    main()
  File "/media/tai/6TB/Projects/InterFaceGAN/InterFaceGAN/generate_data.py", line 65, in main
    model = StyleGANGenerator(args.model_name, logger)
  File "/media/tai/6TB/Projects/InterFaceGAN/InterFaceGAN/models/stylegan_generator.py", line 42, in __init__
    super().__init__(model_name, logger)
  File "/media/tai/6TB/Projects/InterFaceGAN/InterFaceGAN/models/base_generator.py", line 95, in __init__
    self.load()
  File "/media/tai/6TB/Projects/InterFaceGAN/InterFaceGAN/models/stylegan_generator.py", line 63, in load
    self.model.load_state_dict(state_dict)
  File "/media/tai/6TB/anaconda3/envs/InterfaceGAN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for StyleGANGeneratorModel:
	Unexpected key(s) in state_dict: "synthesis.output8.conv.weight", "synthesis.output8.bias". 
	size mismatch for synthesis.output4.conv.weight: copying a param with shape torch.Size([3, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
	size mismatch for synthesis.output5.conv.weight: copying a param with shape torch.Size([3, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 128, 1, 1]).
	size mismatch for synthesis.output6.conv.weight: copying a param with shape torch.Size([3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 64, 1, 1]).
	size mismatch for synthesis.output7.conv.weight: copying a param with shape torch.Size([3, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 32, 1, 1]).
`
I guess it is because InterFaceGAN is set to work with models being trained with 1024x1024 images by default.

Where should I modify so that I can load my 512x512 model?

Thank you very much!

**Comment by ShenYujun** [comment]
Please pull the lateset version, and set the `resolution` as 512 in file `models/model_settings.py`.

**Comment by doantientai** [comment]
Thank you @ShenYujun but unfortunately I still receive the same error with the new latest version.

Below is the config that I added to the MODEL_POOL in model_settings.py

    'style_gan_512': {
        'tf_model_path': 'models/pretrain/styleGAN/network-snapshot-006840.pkl',
        'model_path': 'models/pretrain/styleGAN/network-snapshot-006840.pth',
        'gan_type': 'stylegan',
        'dataset_name': 'style_gan_512',
        'latent_space_dim': 512,
        'w_space_dim': 512,
        'resolution': 512,
        'min_val': -1.0,
        'max_val': 1.0,
        'output_channels': 3,
        'channel_order': 'RGB',
        'fused_scale': 'auto',
    },

**Comment by doantientai** [comment]
Oh actually, I can generate 10k images using the original StyleGan repo that I used to train my model, then use them for train_boundary.py later, right?

**Comment by ShenYujun** [comment]
Have you deleted the converted pytorch model and re-convert the tensorflow version? In your case, please delete`models/pretrain/styleGAN/network-snapshot-006840.pth` and try to run `generate_data.py` again.

Indeed, you can use the original repo to generate data, but I still recommend to go through the entire process, since our repo will save not only the synthesized image, but also the latent codes `z` and `w`.

**Comment by doantientai** [comment]
Oh, my bad. That's true. It's working after I removed the converted model. Thanks @ShenYujun
