### ISSUE TITLE
Attributes predictor

### ISSUE THREAD

**Issue by muxgt** [ShenYujun/InterFaceGAN#23]
Hi! Thanks for your great research!
Is there any chance you can provide attributes predictor that you used for finding boundaries? I didn't really get about scores that it should give to attributes on the pictures.
Also for example for binary attributes like glasses/no glasses is it possible to manually put labels of say 1 for glasses, 0 for no glasses and feed this data to train a new boundary?

**Comment by ShenYujun** [comment]
Sorry that we will not release the attribute model. However, you can manually label a collection of synthesized images and then train a linear boundary for further manipulation.

**Comment by muxgt** [comment]
So is there a format of what labels should be? Or 1 and 0 will be OK?

**Comment by ShenYujun** [comment]
Yes, 0/1 is enough.

**Comment by muxgt** [comment]
OK, thanks!

**Comment by krishnamecho** [comment]
@muxgt 
Were you able to determine the attribute scores?
