### ISSUE TITLE
Questions about the truncation module.

### ISSUE THREAD

**Issue by mehameha998** [ShenYujun/InterFaceGAN#24]
I have a question on your implementation of the truncation module.  Why do the first 9 channels of the W+ code are same? It looks like you separate W+ code into just 2 blocks but 18 blocks? This is strange for that in the official code each channel(I mean 18, not 512) of W+ code is different.

**Comment by ShenYujun** [comment]
Sorry, but I am confused. Can you be more precise?

In the official model, when you do not perform truncation trick, all codes for 18 layers should be the same if I remember correctly. If you do perform the truncation trick, the trick only takes effect on several bottom layers.

**Comment by mehameha998** [comment]
Opzz... I though them truncate code on all layers. Anyway, my question is about the different truncation schedule between your code and official code. In your code, W code only is truncated twice.

**Comment by mehameha998** [comment]
It looks like that this trick won't decrease the image quality a lot. And even though you didn't adopt the mean W of pretrained model, the generated images still keep high quality.

**Comment by ShenYujun** [comment]
Can you point out where 'W code only is truncated twice' and 'you didn't adopt the mean W of pretrained model'?

```
def forward(self, w):
  if len(w.shape) == 2:
    w = w.view(-1, 1, self.w_space_dim).repeat(1, self.num_layers, 1)
  if self.use_truncation:
    w_avg = self.w_avg.view(1, 1, self.w_space_dim)
    w = w_avg + (w - w_avg) * self.truncation
  return w
```

Above is the code Line 322-328 in file `models/stylegan_generator_model.py`. I think the mean W of pretrained model is used as `w_avg` and W is truncated only once with `w = w_avg + (w - w_avg) * self.truncation`. There must be some misunderstanding.

**Comment by mehameha998** [comment]
I check the paper and code again. I feel embarrassed to ask such naive question and cause your confusion...... Sorry :P
