### ISSUE TITLE
the change of smile when increase the distance of the "glasses" attribute

### ISSUE THREAD

**Issue by zzxzzx123** [ShenYujun/InterFaceGAN#26]
Hi,thanks for your great research.
I have a problem when I apply the "pggan_celebahq_eyeglasses_c_age_gender_boundary.npy" on the pre-trained pggan model. With the conditional manipulation on "glasses" attribute , the smile changes gradually. Here are the results. 
![000_001](https://user-images.githubusercontent.com/35441169/69525326-d754d100-0fa2-11ea-9061-5976a9d2ac62.jpg)
![000_004](https://user-images.githubusercontent.com/35441169/69525338-dd4ab200-0fa2-11ea-86d4-60b2998ab67b.jpg)
![008_001](https://user-images.githubusercontent.com/35441169/69525361-eb98ce00-0fa2-11ea-9951-15488430b520.jpg)
![008_005](https://user-images.githubusercontent.com/35441169/69525494-2b5fb580-0fa3-11ea-8252-51b9dbf945b3.jpg)
But the attributes seem to be uncorrelated in your paper. 
Could you explained it for me?

**Comment by ShenYujun** [comment]
The `eyeglasses` attribute for PGGAN may not be that accurate, since there are not enough faces with eyeglasses among synthesized data. According to the boundary correlation, however, they should be disentangled with each other.

**Comment by zzxzzx123** [comment]
Thanks for your answer. I will train a svm classifier to test it again.
