### ISSUE TITLE
More explanation about the calculation about the boundary on two condition

### ISSUE THREAD

**Issue by BERYLSHEEP** [ShenYujun/InterFaceGAN#28]
https://github.com/ShenYujun/InterFaceGAN/blob/b707e942187f464251f855c92f7009b8cf13bf03/utils/manipulator.py#L189

I found that the code also supports two condition boundary editing. But I am confused about the calculation. Can anyone make an explanation for me? Thanks a lot!

**Comment by ShenYujun** [comment]
Suppose we have a primal boundary $b_0$ and two other boundaries $b_1$ and $b_2$ to condition on.

We would like to find $\alpha$ and $\beta$ to get a new boundary $b = b_0 - \alpha b_1 - \beta b_2$, such that $b^T b_1 = 0$ and $b^T b_2 = 0$.

The above equations lead to
${b_0}^T b_1 - \alpha {b_1}^T b_1 - \beta {b_2}^T b_1 = 0$
${b_0}^T b_2 - \alpha {b_1}^T b_2 - \beta {b_2}^T b_2 = 0$

Now we can simply solve $\alpha$ and $\beta$.
