### ISSUE TITLE
How to get the pose boundary?

### ISSUE THREAD

**Issue by BERYLSHEEP** [ShenYujun/InterFaceGAN#29]
Hello! I am confused about how to get the pose boundary. The paper said that the auxiliary attribute prediction model predicts the 5-point facial landmarks. I find the label about the facial landmarks is coordinate in the CelebFace Dataset. The paper said that turning right is the corresponding positive direction. How did you turn the coordinate into binary code that represents the direction?

**Comment by ShenYujun** [comment]
I think there should be many feasible ways. For example, you can compute the midpoint of two eyes, and see where it locates in the image. Taking the middle vertical line as a reference, you can get a binary label :). Also, you can also try to estimate the yaw pose based on the five landmarks with some basic geometry and use angle 0 for separation. Or, you can try something else. Good luck!
