### ISSUE TITLE
W space or W+ space

### ISSUE THREAD

**Issue by BERYLSHEEP** [ShenYujun/InterFaceGAN#30]
hello! The GitHub provides us some boundaries about the W space in StyleGAN. But I found that the code contains two configurations which are W space and W+ space. So I wonder if all the boundaries label W in paper and Github are corresponding to W space? There is no provided W+ space boundaries and no W+ space results in the paper? Thanks a lot.

**Comment by ShenYujun** [comment]
Yes, W+ space is not mentioned in the paper. But considering some GAN inversion methods are using W+ space (like [stylegan-encoder ](https://github.com/Puzer/stylegan-encoder) and [image2stylegan](https://arxiv.org/abs/1904.03189)), we also provide boundaries for W+ space here.

**Comment by zhongtao93** [comment]
Hi, how much better is the editability of W+ space than that of W space?
