### ISSUE TITLE
Can we use pretrained models of stylegan for getting attribute scores??

### ISSUE THREAD

**Issue by sandhyalaxmiK** [ShenYujun/InterFaceGAN#33]
Hi,

1.Can we use pretrained attribute classification model files like 'celebahq-classifier-19-eyeglasses.pkl'  for attribute scores of the models???

2. can we use the pth file generated from this repository https://github.com/rosinality/stylegan2-pytorch ??

**Comment by ShenYujun** [comment]
1. Yes. You can use any attribute classifier you want. This repo only requires a collection of (latent_code, attribute_score) pairs for boundary training.

2. Yes. You can wrap any model based on `models/base_generator.py`.
