### ISSUE TITLE
created stylegan2.pth file. Further steps for training??????

### ISSUE THREAD

**Issue by sandhyalaxmiK** [ShenYujun/InterFaceGAN#34]
I am able to execute stylegan2-pytorch and obtained stylegan2-ffhq-config-f.pt file . Attaching here:

https://drive.google.com/file/d/1fqBNoicjUG1dHlunQAQQQ9KVpN4x2_Yn/view?usp=sharing

 Can any suggestions for how to use this pt file for training and getting boundaries???

Thanks in advance.

_Originally posted by @sandhyalaxmiK in https://github.com/ShenYujun/InterFaceGAN/issues/31#issuecomment-579197445_

**Comment by ShenYujun** [comment]
Use an off-the-shelf classifier to prepare (latent_code, semantic_score) pairs. And then use `train_boundary.py` for boundary search.
