### ISSUE TITLE
Do you have plan to release code of attribute predictor?

### ISSUE THREAD

**Issue by jychoi118** [ShenYujun/InterFaceGAN#37]
I want to try training boundaries, and realized that i need trained attribute score predictor to generate attribute inference results. Do you have plan to release code of attribute predictor?

**Comment by ShenYujun** [comment]
We have other plans on the attribute predictors, however, you can use the predictors provided by [StyleGAN](https://github.com/NVlabs/stylegan) (see `stylegan/metrics/linear_separability.py`). We will provide the PyTorch version of those predictors from StyleGAN in the near future. Hope this information will help.

**Comment by orpatashnik** [comment]
Any update about the release of the pytorch version of the predictors?
