### ISSUE TITLE
Requirments.txt and pre-trained models

### ISSUE THREAD

**Issue by gogoAiEnity** [ShenYujun/InterFaceGAN#4]
Great contribution and git my friends, thanks so much for posting this open to the community to use. 

Would like to ask several questions:

1) Any way you can provide a requirements.txt file in order for those who don't have the libraries to easily use your git?

2) Can you link to the appropriate pre-trained models and where to download them? I have tried using the PGGAN from the github and yet the edit.py isn't working.

Thanks again!

**Comment by ShenYujun** [comment]
We use `python 3.7` with requirements `pytorch-1.1.0` for the main project, `tensorflow-1.12.2` for converting the official tensorflow models to pytorvch version, and `sklearn-0.21.2` for SVM training. Please see the header of `README`. You may also need to install `tqdm` package for showing progress bar.

PGGAN model and StyleGAN model can be found on their official repos. Please download them and put them under `models/pretrain` folder.

What error do you run into when you say "edit.py isn't working"?

**Comment by gogoAiEnity** [comment]
Thanks for that, I was just saying a requirements.txt would make it easier for people to use on demand and might look friendlier to those downloading. 

The edit.py isn't finding the stylegan pretrained model.. which is why I was asking about the pretrained model links incase I was using the wrong one.
